import type { Store } from "./store.types";

export const initialState: Store = {
  gender: {
    isLoadingGetList: false,
    isSuccessGetList: false,
    isErrorGetList: false,
    dataGetList: null,
    errorGetList: null,
  },

  state: {
    isLoadingGetList: false,
    isSuccessGetList: false,
    isErrorGetList: false,
    dataGetList: null,
    errorGetList: null,
  },

  country: {
    isLoadingGetList: false,
    isSuccessGetList: false,
    isErrorGetList: false,
    dataGetList: null,
    errorGetList: null,
  },

  city: {
    isLoadingGetList: false,
    isSuccessGetList: false,
    isErrorGetList: false,
    dataGetList: null,
    errorGetList: null,
  },

  sector: {
    isLoadingGetList: false,
    isSuccessGetList: false,
    isErrorGetList: false,
    dataGetList: null,
    errorGetList: null,
  },

  natureOfBusiness: {
    isLoadingGetList: false,
    isSuccessGetList: false,
    isErrorGetList: false,
    dataGetList: null,
    errorGetList: null,
  },

  typeOfBusiness: {
    isLoadingGetList: false,
    isSuccessGetList: false,
    isErrorGetList: false,
    dataGetList: null,
    errorGetList: null,
  },

  currency: {
    isLoadingGetList: false,
    isSuccessGetList: false,
    isErrorGetList: false,
    dataGetList: null,
    errorGetList: null,
  },

  billingType: {
    isLoadingGetList: false,
    isSuccessGetList: false,
    isErrorGetList: false,
    dataGetList: null,
    errorGetList: null,
  },

  commonInternal: {
    addAttachment: [],
    fileUrl: [],
    currentPage: 1,
    totalPages: 0,
    rowsPerPage: 5,
    isCollapsed: false,
    isCalenderOpen: false,
    matches: [],
    highlightedIndex: 0,
    roleSearchTerm: "",
    loading: false,
    errors: {},
    search: {},
    light: false,
    orderBy: "",
    orderDirection: "",
  },

  orgAdminModal: {
    adminModalOpen: false,
    adminTab: "org",
    orgTab: "info",
    domainTab: "begin",
    domainSelectTab: "free",
    existingTab: "dummy",
    newTab: "terms",
    planTab: "detail",
    isLoadingCreateOrg: false,
    isSuccessCreateOrg: false,
    isErrorCreateOrg: false,
    errorCreateOrg: null,
  },

  auth: {
    email: "",
    userId: "",
    orgAuthId: null,
    authToken: null,

    isLoadingCheckEmail: false,
    isSuccessCheckEmail: false,
    isErrorCheckEmail: false,
    errorCheckEmail: null,

    isLoadingSignup: false,
    isSuccessSignup: false,
    isErrorSignup: false,
    errorSignup: null,

    isLoadingVerifyEmail: false,
    isSuccessVerifyEmail: false,
    isErrorVerifyEmail: false,

    isLoadingMobileOtp: false,
    isSuccessMobileOtp: false,
    isErrorMobileOtp: false,

    isLoadingVerifyMobile: false,
    isSuccessVerifyMobile: false,
    isErrorVerifyMobile: false,

    isLoadingUpdateMfa: false,
    isSuccessUpdateMfa: false,
    isErrorUpdateMfa: false,

    isLoadingLogin: false,
    isSuccessLogin: false,
    isErrorLogin: false,
    errorLogin: null,

    isLoadingVerifyLoginOtp: false,
    isSuccessVerifyLoginOtp: false,
    isErrorVerifyLoginOtp: false,

    isLoadingForgotPassword: false,
    isSuccessForgotPassword: false,
    isErrorForgotPassword: false,
    errorForgotPassword: null,

    isLoadingVerifyForgotPasswordOtp: false,
    isSuccessVerifyForgotPasswordOtp: false,
    isErrorVerifyForgotPasswordOtp: false,

    isLoadingResetPassword: false,
    isSuccessResetPassword: false,
    isErrorResetPassword: false,
    errorResetPassword: null,

    isLoadingResendOtp: false,
    isSuccessResendOtp: false,
    isErrorResendOtp: false,

    isLoadingVerifyMfaOtp: false,
    isSuccessVerifyMfaOtp: false,
    isErrorVerifyMfaOtp: false,
  },

  profile: {
    profileData: null,
    isLoadingGetProfile: false,
    isSuccessGetProfile: false,
    isErrorGetProfile: false,
    errorGetProfile: null,

    isLoadingUpdateProfile: false,
    isSuccessUpdateProfile: false,
    isErrorUpdateProfile: false,
    errorUpdateProfile: null,

    isLoadingUploadDp: false,
    isSuccessUploadDp: false,
    isErrorUploadDp: false,
    uploadedDpData: null,
  },

  organisationBasic: {
    organisationBasicData: null,
    isLoadingGetOrgBasic: false,
    isSuccessGetOrgBasic: false,
    isErrorGetOrgBasic: false,
    errorGetOrgBasic: null,

    isLoadingCreateOrgBasic: false,
    isSuccessCreateOrgBasic: false,
    isErrorCreateOrgBasic: false,
    errorCreateOrgBasic: null,

    isLoadingUpdateOrgBasic: false,
    isSuccessUpdateOrgBasic: false,
    isErrorUpdateOrgBasic: false,
    errorUpdateOrgBasic: null,
  },

  businessUnit: {
    businessUnitList: [],
    selectedBusinessUnit: null,
    totalElements: 0,
    totalPages: 0,
    isLoadingGetList: false,
    isSuccessGetList: false,
    isErrorGetList: false,
    isLoadingDetail: false,
    isSuccessDetail: false,
    isErrorDetail: false,
    isLoadingCreate: false,
    isSuccessCreate: false,
    isErrorCreate: false,
  },

  businessUnitLocation: {
    businessUnitLocationList: [],
    selectedBusinessUnitLocation: null,
    totalElements: 0,
    totalPages: 0,
    isLoadingGetList: false,
    isSuccessGetList: false,
    isErrorGetList: false,
    isLoadingCreate: false,
    isSuccessCreate: false,
    isErrorCreate: false,
    isLoadingResetPassword: false,
    isSuccessResetPassword: false,
    isErrorResetPassword: false,
  },

  plan: {
    plansData: [],
    isLoadingGetPlans: false,
    isSuccessGetPlans: false,
    isErrorGetPlans: false,
    errorGetPlans: null,
  },

  client: {
    clientList: [],
    selectedClient: null,
    totalElements: 0,
    totalPages: 0,
    isLoadingGetList: false,
    isSuccessGetList: false,
    isErrorGetList: false,
    isLoadingCreate: false,
    isSuccessCreate: false,
    isErrorCreate: false,
    isLoadingUpdate: false,
    isSuccessUpdate: false,
    isErrorUpdate: false,
    isLoadingDelete: false,
    isSuccessDelete: false,
    isErrorDelete: false,
  },

  project: {
    projectList: [],
    selectedProject: null,
    totalElements: 0,
    totalPages: 0,
    isLoadingGetList: false,
    isSuccessGetList: false,
    isErrorGetList: false,
    isLoadingCreate: false,
    isSuccessCreate: false,
    isErrorCreate: false,
    isLoadingUpdate: false,
    isSuccessUpdate: false,
    isErrorUpdate: false,
    isLoadingDelete: false,
    isSuccessDelete: false,
    isErrorDelete: false,
  },

  team: {
    teamList: [],
    selectedTeam: null,
    totalElements: 0,
    totalPages: 0,
    isLoadingGetList: false,
    isSuccessGetList: false,
    isErrorGetList: false,
    isLoadingCreate: false,
    isSuccessCreate: false,
    isErrorCreate: false,
    isLoadingUpdate: false,
    isSuccessUpdate: false,
    isErrorUpdate: false,
    isLoadingDelete: false,
    isSuccessDelete: false,
    isErrorDelete: false,
  },

  employee: {
    employeeList: [],
    isLoadingGetList: false,
    isSuccessGetList: false,
    isErrorGetList: false,
  },

  organisationDashboard: {
    isLoadingStats: false,
    isSuccessStats: false,
    isErrorStats: false,
    statsData: null,
    errorStats: null,
    isLoadingProjectsOverview: false,
    isSuccessProjectsOverview: false,
    isErrorProjectsOverview: false,
    projectsOverviewData: null,
    errorProjectsOverview: null,
    isLoadingEmployeeOverview: false,
    isSuccessEmployeeOverview: false,
    isErrorEmployeeOverview: false,
    employeeOverviewData: null,
    errorEmployeeOverview: null,
    isLoadingTopClients: false,
    isSuccessTopClients: false,
    isErrorTopClients: false,
    topClientsData: null,
    errorTopClients: null,
    isLoadingProjectHealth: false,
    isSuccessProjectHealth: false,
    isErrorProjectHealth: false,
    projectHealthData: null,
    errorProjectHealth: null,
    isLoadingClientActivities: false,
    isSuccessClientActivities: false,
    isErrorClientActivities: false,
    clientActivitiesData: null,
    errorClientActivities: null,
  },

  support: {
    supportTypes: [],
    relatedModules: [],
    isLoadingSupportTypes: false,
    isSuccessSupportTypes: false,
    isErrorSupportTypes: false,
    isLoadingRelatedModule: false,
    isSuccessRelatedModule: false,
    isErrorRelatedModule: false,
    isLoadingCreate: false,
    isSuccessCreate: false,
    isErrorCreate: false,
  },
};
